# Generated by Django 5.0.4 on 2024-04-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("integrations", "0002_agent_alter_bot_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="integrations.agent",
            ),
        ),
        migrations.DeleteModel(
            name="Agent",
        ),
    ]
