# Generated by Django 5.0.4 on 2024-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="refresh_token",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="token_uri",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="thirdparty",
            field=models.CharField(
                choices=[
                    ("gmail", "Google Mail"),
                    ("google-calender", "Google Calender"),
                    ("google-document", "Google Document"),
                    ("google-drive", "Google Drive"),
                    ("google-sheet", "Google Sheet"),
                    ("salesforce", "Salesforce"),
                    ("slack", "Slack"),
                ],
                max_length=25,
            ),
        ),
    ]
