# Generated by Django 5.0.4 on 2024-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="state",
            field=models.CharField(
                default="ba728c2d4c0db0e5bae7ebce60f61cf9c8b549637be6c884c11781ff69da683d",
                max_length=255,
            ),
        ),
    ]
