# Generated by Django 5.0.4 on 2024-04-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_feedback_agent_delete_agent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedBack",
        ),
    ]
