# Generated by Django 5.0.4 on 2024-06-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agent_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="instance_url",
            field=models.URLField(
                blank=True, help_text="For Salesforce agent", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="state",
            field=models.CharField(
                default="692f7cea8e4f2f410f164964d10c72319f99636f1380ebdd6eb7cf670f8cb95e",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="thirdparty",
            field=models.CharField(
                choices=[
                    ("google-workspace", "Google Workspace"),
                    ("zoho-workspace", "Zoho Workspace"),
                    ("salesforce", "Salesforce"),
                    ("slack", "Slack"),
                ],
                max_length=50,
            ),
        ),
    ]
