# Generated by Django 5.0.4 on 2024-06-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="auth_url",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="token_url",
        ),
    ]
