# Generated by Django 5.0.4 on 2024-06-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0002_remove_integration_auth_url_remove_integration_scope_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="thirdparty",
            field=models.CharField(
                choices=[
                    ("google-workspace", "Google Workspace"),
                    ("zoho-workspace", "Zoho Workspace"),
                    ("salesforce", "Salesforce"),
                    ("slack", "Slack"),
                ],
                max_length=25,
            ),
        ),
    ]
