# Generated by Django 5.0.4 on 2024-04-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_agent_alter_bot_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="scopes",
        ),
    ]
