# Generated by Django 5.0.4 on 2024-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_alter_integration_thirdparty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="id_token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
