# Generated by Django 5.0.4 on 2024-05-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_alter_agent_id_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="integration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to="integrations.integration",
            ),
            preserve_default=False,
        ),
    ]
