# Generated by Django 5.0.4 on 2024-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_bot_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="is_workspace",
            field=models.BooleanField(
                default=False,
                help_text="Does it comprise multiple agents or a single agent?",
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="is_chat_app",
            field=models.BooleanField(
                help_text="Is it a messaging app integration or other thirdparty integration?"
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="thirdparty",
            field=models.CharField(
                choices=[
                    ("google-workspace", "Google Workspace"),
                    ("google-form", "Google Form"),
                    ("salesforce", "Salesforce"),
                    ("slack", "Slack"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
