# Generated by Django 5.0.4 on 2024-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_state_thirdparty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="thirdparty",
            field=models.CharField(
                choices=[
                    ("google-workspace", "Google Workspace"),
                    ("google-form", "Google Form"),
                    ("salesforce", "Salesforce"),
                    ("slack", "Slack"),
                ],
                max_length=25,
            ),
        ),
    ]
