# Generated by Django 5.0.4 on 2024-04-17 08:43

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_id", models.CharField(max_length=255, null=True)),
                ("user_id", models.CharField(max_length=255)),
                ("enterprise_id", models.CharField(max_length=255, null=True)),
                ("enterprise_name", models.CharField(max_length=255, null=True)),
                ("enterprise_url", models.CharField(max_length=255, null=True)),
                ("team_id", models.CharField(max_length=255, null=True)),
                ("team_name", models.CharField(max_length=255, null=True)),
                ("bot_token", models.CharField(max_length=255, null=True)),
                ("bot_id", models.CharField(max_length=255, null=True)),
                ("bot_user_id", models.CharField(max_length=255, null=True)),
                (
                    "bot_scopes",
                    models.CharField(
                        help_text="Comma separated string", max_length=500, null=True
                    ),
                ),
                (
                    "bot_refresh_token",
                    models.CharField(
                        help_text="Only when token rotation is enabled",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("bot_token_expires_at", models.DateTimeField(null=True)),
                ("user_token", models.CharField(max_length=255, null=True)),
                (
                    "user_scopes",
                    models.CharField(
                        help_text="Comma separated string", max_length=500, null=True
                    ),
                ),
                (
                    "user_refresh_token",
                    models.CharField(
                        help_text="Only when token rotation is enabled",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("user_token_expires_at", models.DateTimeField(null=True)),
                ("incoming_webhook_url", models.CharField(max_length=255, null=True)),
                (
                    "incoming_webhook_channel",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "incoming_webhook_channel_id",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "incoming_webhook_configuration_url",
                    models.CharField(max_length=255, null=True),
                ),
                ("is_enterprise_install", models.BooleanField(default=False)),
                ("token_type", models.CharField(max_length=255, null=True)),
                ("installed_at", models.DateTimeField()),
                ("custom_values", models.JSONField(null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slackbots",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
