# Generated by Django 5.0.4 on 2024-04-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agent_refresh_token_agent_token_uri_and_more"),
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to="agents.agent",
            ),
        ),
    ]
