# Generated by Django 5.0.4 on 2024-04-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="dislike",
        ),
    ]
